language: node_js
node_js:
  - "6"
deploy:
  provider: npm
  email: vi@ole.org
  api_key:
    secure: gWNGVAqklHRLtfzJU9buUo6leqiXHoiMMZMkZ1l97qcyo5I6dHoWmWrHds2kes38bUTIUcBfGAA4/evtHvUGpzsTZWBDdZJFOB+l4Fus7wd9iKJ4aUJ5TmEBQ7P0ytCjMeGNb7xIPXaYli90c9WBdV8aOd/pmC40ubxnAMxiQOLiy0ws8RCvjtArNzcg+bFsyrTygnERATEJy2ReD3mw7ExBGMqSXILAnrw+F758uYoIiXfVIXsE5dMONz4zhyUV3hF3d/393B2/ugW5Chgy+Axr/KPn5FHgi//n6m9SsRAPENMnimd9QVZiFOMc0wxHYsPfMJQALdNJOeUM3iNFkqBKUUNndH/iUiclyupa+r4CinjkdPBUetJ/Lpy1b3oc5/WK/yczJYDqLnX1Bhi0GSSyERVbXhhz/kRxNE24WXD8ILciOwaE4XAf3YSxKOGW0vt65e23LipSfDeNuq1IPAUSPh4cW70yyiL7xq1e+jLOCTd/92LxnjS/9wXS3OgRbvoYg3RTQhIctT/m5Lr6eYgqgWEilEdhDiHSD19mDYgkxOjV2RVNh5bME0xtvqQyqfrELrNb9xamnw4IpnknoBz6fYPD34EHo9yoz1Tavm7sPL65qbig2Afq+f29gEDdtWx0mmUIfSx4pkWq/aiaZeg12U639NPNXibqz2m37jQ=
  skip_cleanup: true
  on:
    tags: true
    repo: ole-vi/cli
